export const slideOrder = [
  "landing",
  "goal",
  "warmup",
  "powerup",
  "team",
  "final-check",
  "boss",
  "independent",
];

export const lessonDecks = {
  fractions: {
    id: "fractions",
    icon: "🚀",
    grade: "5th Grade",
    lessonDate: "March 31, 2026",
    lessonTime: "10:00 AM",
    title: "Math Quest!",
    topbarSubtitle: "Interactive fraction lesson deck",
    missionTheme: "Fraction Adventure",
    missionSummary: "Compare, add, subtract, multiply, and divide fractions through colorful challenge cards.",
    heroSubtitle: "Today’s mission: Fraction Team Time",
    heroCta: "Exploring Fraction Operations",
    heroModes: ["🚀", "💎", "🎲", "🧮"],
    goal: "I can compare fractions with unlike denominators and explain my thinking using visual models.",
    successCriteria: [
      "I can identify equivalent fractions",
      "I can find common denominators",
      "I can compare fractions using symbols",
      "I can explain my reasoning",
    ],
    vocabulary: [
      ["Equivalent", "Equal in value"],
      ["Numerator", "Top number"],
      ["Denominator", "Bottom number"],
      ["Common", "Shared by all"],
    ],
    warmup: {
      timerSeconds: 120,
      tip: "Look for common denominators when adding or subtracting fractions. Find the least common multiple first.",
      problems: [
        { id: "w1", label: "1", title: "Problem 1", prompt: "3/4 + 1/8 = ?", answer: "7/8" },
        { id: "w2", label: "2", title: "Problem 2", prompt: "2/3 × 6/7 = ?", answer: "4/7" },
        { id: "w3", label: "3", title: "Problem 3", prompt: "5/6 - 1/4 = ?", answer: "7/12" },
      ],
      bonusBank: ["7/8 - 1/4 = ?", "3/5 + 2/15 = ?", "5/12 + 1/6 = ?", "4/9 - 1/3 = ?"],
    },
    powerup: {
      title: "Math Power-Up",
      subtitle: "Today’s Mission: Master Fraction Operations",
      exampleProblem: "3/4 + 2/5 = ?",
      storyProblems: [
        {
          id: "s1",
          title: "Story Problem 1",
          prompt: "A recipe needs 2/3 cup of sugar for one batch. Maya makes 3 batches. Which operation should she use to find the total sugar needed?",
          operation: "multiply",
          why: "She has the same amount, 2/3 cup, repeated 3 times, so she should multiply.",
        },
        {
          id: "s2",
          title: "Story Problem 2",
          prompt: "Leo has 5/6 yard of ribbon and uses 1/3 yard for a project. Which operation should he use to find how much ribbon is left?",
          operation: "subtract",
          why: "He starts with an amount and takes some away, so he should subtract.",
        },
      ],
      strategyCopy: {
        "step-1": "Find the LCD: The least common denominator of 4 and 5 is 20.",
        "step-2": "Convert: 3/4 becomes 15/20 and 2/5 becomes 8/20.",
        "step-3": "Add: 15/20 + 8/20 = 23/20, which is 1 3/20.",
      },
      strategySteps: [
        "Identify the operation: decide whether you add, subtract, multiply, or divide.",
        "Find common denominators: use the LCD for addition and subtraction.",
        "Convert fractions: rename fractions with the common denominator.",
        "Perform the operation: keep the denominator the same when adding or subtracting.",
        "Simplify the answer: reduce to lowest terms if needed.",
      ],
    },
    team: {
      title: "Team Solve",
      subtitle: "Work with a partner to solve these problems together.",
      problems: [
        { id: "t1", label: "A", title: "Problem A", prompt: "1/2 + 3/10 = ?", answer: "4/5" },
        { id: "t2", label: "B", title: "Problem B", prompt: "3/5 × 5/9 = ?", answer: "1/3" },
        { id: "t3", label: "C", title: "Problem C", prompt: "7/8 - 1/2 = ?", answer: "3/8" },
        { id: "t4", label: "D", title: "Problem D", prompt: "3/4 ÷ 1/2 = ?", answer: "3/2" },
      ],
    },
    finalCheck: {
      question: "A recipe calls for 3/4 cup of flour. If you want to make 2/3 of the recipe, how much flour do you need? Show your work and explain your reasoning.",
      teacherNote: "Next Steps: Use this information to plan reteaching groups and identify students who need additional support.",
    },
    boss: {
      title: "Challenge Zone: Boss Battle",
      subtitle: "Ready to tackle the ultimate math challenge?",
      scenario: "A bakery has 3/4 of a chocolate cake and 2/5 of a vanilla cake left. If they sell 1/8 of the chocolate cake and 1/10 of the vanilla cake, how much of each cake remains? What is the total amount of cake left?",
      hints: [
        "Strategy: Use a bar model to visualize the fractions. Draw two bars representing the chocolate and vanilla cakes, then shade the parts that are sold.",
        "Hint 2: Subtract 1/8 from 3/4 to find the chocolate cake left. Subtract 1/10 from 2/5 to find the vanilla cake left.",
        "Hint 3: Rewrite each pair with common denominators first, then add the remaining cake amounts together.",
      ],
      strategies: ["Draw a diagram", "Break into smaller parts", "Check equivalent fractions"],
    },
    independent: {
      levels: [
        {
          id: "easy",
          title: "Level 1: Warm-Up",
          difficulty: "Easy",
          accent: "green",
          note: "✔️ Check your work with a partner",
          problems: [
            { id: "i1", number: "1", prompt: "1/3 + 1/6 = ?", answer: "1/2" },
            { id: "i2", number: "2", prompt: "4/9 × 3/8 = ?", answer: "1/6" },
          ],
        },
        {
          id: "medium",
          title: "Level 2: Challenge",
          difficulty: "Medium",
          accent: "gold",
          note: "✔️ Show your strategy",
          problems: [
            { id: "i3", number: "3", prompt: "11/12 - 1/3 = ?", answer: "7/12" },
            { id: "i4", number: "4", prompt: "5/6 ÷ 5/12 = ?", answer: "2" },
          ],
        },
        {
          id: "hard",
          title: "Boss Battle",
          difficulty: "Hard",
          accent: "red",
          note: "✔️ Explain your reasoning",
          problems: [
            { id: "i5", number: "5", prompt: "2/3 + 3/4 - 1/6 = ?", answer: "5/4" },
          ],
        },
      ],
    },
  },
  decimals: {
    id: "decimals",
    icon: "⚡",
    grade: "5th Grade",
    lessonDate: "April 2, 2026",
    lessonTime: "9:30 AM",
    title: "Math Quest!",
    topbarSubtitle: "Interactive decimal lesson deck",
    missionTheme: "Decimal Dash",
    missionSummary: "Read, compare, add, and multiply decimals with visual models and timed practice.",
    heroSubtitle: "Today’s mission: Decimal Dash",
    heroCta: "Exploring Decimal Operations",
    heroModes: ["⚡", "📏", "🏁", "🧠"],
    goal: "I can compare and solve decimal problems using place value strategies.",
    successCriteria: [
      "I can line up decimal points",
      "I can compare decimals using place value",
      "I can estimate before solving",
      "I can explain my reasoning clearly",
    ],
    vocabulary: [
      ["Tenths", "One part out of ten"],
      ["Hundredths", "One part out of one hundred"],
      ["Place value", "A digit’s value by position"],
      ["Estimate", "A close answer"],
    ],
    warmup: {
      timerSeconds: 150,
      tip: "Line up decimal points before adding or subtracting. Estimate first so you know if your answer makes sense.",
      problems: [
        { id: "w1", label: "1", title: "Problem 1", prompt: "2.4 + 1.38 = ?", answer: "3.78" },
        { id: "w2", label: "2", title: "Problem 2", prompt: "5.2 - 0.67 = ?", answer: "4.53" },
        { id: "w3", label: "3", title: "Problem 3", prompt: "0.6 × 0.4 = ?", answer: "0.24" },
      ],
      bonusBank: ["4.5 + 0.08 = ?", "7.1 - 2.95 = ?", "0.3 × 0.7 = ?", "6.24 + 1.5 = ?"],
    },
    powerup: {
      title: "Decimal Power-Up",
      subtitle: "Today’s Mission: Make Place Value Work for You",
      exampleProblem: "3.6 + 0.45 = ?",
      storyProblems: [
        {
          id: "s1",
          title: "Story Problem 1",
          prompt: "A tank has 4.5 liters of water. Sam pours in 1.25 more liters. Which operation should she use to find the new total?",
          operation: "add",
          why: "The amount is increasing because more water is being added, so she should add.",
        },
        {
          id: "s2",
          title: "Story Problem 2",
          prompt: "A runner finished 8.2 kilometers of a race and still has 1.75 kilometers left. Which operation should she use to find the full race distance?",
          operation: "add",
          why: "To find the whole distance, she combines the part finished and the part left, so she should add.",
        },
      ],
      strategyCopy: {
        "step-1": "Line up decimals: Write 3.60 + 0.45 so each place value matches.",
        "step-2": "Add place by place: Hundredths first, then tenths, then ones.",
        "step-3": "Check the sum: 3.60 + 0.45 = 4.05.",
      },
      strategySteps: [
        "Estimate first so you know the answer should be a little more than 4.",
        "Line up decimal points to keep place values matched.",
        "Add or subtract from right to left.",
        "Regroup when needed.",
        "Check whether your answer matches your estimate.",
      ],
    },
    team: {
      title: "Partner Precision",
      subtitle: "Work with a partner to solve decimal problems together.",
      problems: [
        { id: "t1", label: "A", title: "Problem A", prompt: "4.7 + 2.06 = ?", answer: "6.76" },
        { id: "t2", label: "B", title: "Problem B", prompt: "8.3 - 1.45 = ?", answer: "6.85" },
        { id: "t3", label: "C", title: "Problem C", prompt: "0.9 × 0.5 = ?", answer: "0.45" },
        { id: "t4", label: "D", title: "Problem D", prompt: "6.08 + 0.32 = ?", answer: "6.4" },
      ],
    },
    finalCheck: {
      question: "A ribbon is 2.5 meters long. You use 0.75 meter for one project and 0.8 meter for another. How much ribbon is left? Show your work and explain your reasoning.",
      teacherNote: "Next Steps: Notice who lines up decimal points correctly and who still needs support with regrouping.",
    },
    boss: {
      title: "Decimal Boss Battle",
      subtitle: "Ready to take on a multi-step decimal challenge?",
      scenario: "A school store sold 3.75 liters of juice in the morning and 2.4 liters in the afternoon. It started with 8.5 liters. How much juice is left at the end of the day?",
      hints: [
        "Strategy: Estimate first. About 3.75 + 2.4 is a little more than 6 liters sold.",
        "Hint 2: Add the amounts sold together before subtracting from the starting amount.",
        "Hint 3: Line up all decimal points when you subtract.",
      ],
      strategies: ["Estimate first", "Line up decimals", "Check with inverse operation"],
    },
    independent: {
      levels: [
        {
          id: "easy",
          title: "Level 1: Warm-Up",
          difficulty: "Easy",
          accent: "green",
          note: "✔️ Compare your estimate first",
          problems: [
            { id: "i1", number: "1", prompt: "2.1 + 0.4 = ?", answer: "2.5" },
            { id: "i2", number: "2", prompt: "7.0 - 2.8 = ?", answer: "4.2" },
          ],
        },
        {
          id: "medium",
          title: "Level 2: Challenge",
          difficulty: "Medium",
          accent: "gold",
          note: "✔️ Show your place value thinking",
          problems: [
            { id: "i3", number: "3", prompt: "3.45 + 1.27 = ?", answer: "4.72" },
            { id: "i4", number: "4", prompt: "9.6 - 3.84 = ?", answer: "5.76" },
          ],
        },
        {
          id: "hard",
          title: "Boss Battle",
          difficulty: "Hard",
          accent: "red",
          note: "✔️ Explain why the decimal points matter",
          problems: [
            { id: "i5", number: "5", prompt: "2.75 + 1.6 - 0.85 = ?", answer: "3.5" },
          ],
        },
      ],
    },
  },
  geometry: {
    id: "geometry",
    icon: "📐",
    grade: "4th Grade",
    lessonDate: "April 4, 2026",
    lessonTime: "1:15 PM",
    title: "Math Quest!",
    topbarSubtitle: "Interactive geometry lesson deck",
    missionTheme: "Geometry Galaxy",
    missionSummary: "Classify shapes, compare angles, and solve perimeter challenges with hands-on prompts.",
    heroSubtitle: "Today’s mission: Shape Sleuth Squad",
    heroCta: "Exploring Angles and Shapes",
    heroModes: ["📐", "🛰️", "⭐", "🧱"],
    goal: "I can classify shapes and solve perimeter problems using attributes and measurements.",
    successCriteria: [
      "I can identify lines and angles",
      "I can sort shapes by attributes",
      "I can find perimeter of polygons",
      "I can explain how I know",
    ],
    vocabulary: [
      ["Parallel", "Lines that never cross"],
      ["Perimeter", "Distance around a shape"],
      ["Vertex", "A corner point"],
      ["Right angle", "An exact square corner"],
    ],
    warmup: {
      timerSeconds: 180,
      tip: "Count all outer sides for perimeter. Look for angle clues to classify shapes.",
      problems: [
        { id: "w1", label: "1", title: "Problem 1", prompt: "What is the perimeter of a square with side length 6 cm?", answer: "24" },
        { id: "w2", label: "2", title: "Problem 2", prompt: "How many right angles does a rectangle have?", answer: "4" },
        { id: "w3", label: "3", title: "Problem 3", prompt: "A triangle has sides 3, 4, and 5. What is its perimeter?", answer: "12" },
      ],
      bonusBank: ["Name a shape with exactly one pair of parallel sides.", "Find the perimeter of a pentagon with side length 3 cm.", "How many vertices does a hexagon have?", "What type of angle is smaller than a right angle?"],
    },
    powerup: {
      title: "Geometry Power-Up",
      subtitle: "Today’s Mission: Use shape clues wisely",
      exampleProblem: "Rectangle: length 8 cm, width 3 cm. Perimeter = ?",
      strategyCopy: {
        "step-1": "Read the shape clues: A rectangle has two lengths and two widths.",
        "step-2": "Add all sides: 8 + 3 + 8 + 3.",
        "step-3": "Solve: The perimeter is 22 cm.",
      },
      strategySteps: [
        "Name the shape and notice its attributes.",
        "Mark the side lengths you know.",
        "Use repeated addition or multiplication when sides match.",
        "Check that you counted every outer side.",
        "Label your answer with units.",
      ],
    },
    team: {
      title: "Shape Squad",
      subtitle: "Work together to classify and measure shapes.",
      problems: [
        { id: "t1", label: "A", title: "Problem A", prompt: "Rectangle with sides 9 cm and 2 cm. Perimeter = ?", answer: "22" },
        { id: "t2", label: "B", title: "Problem B", prompt: "How many sides does a pentagon have?", answer: "5" },
        { id: "t3", label: "C", title: "Problem C", prompt: "How many vertices does a rectangle have?", answer: "4" },
        { id: "t4", label: "D", title: "Problem D", prompt: "Triangle sides 6, 5, and 4. Perimeter = ?", answer: "15" },
      ],
    },
    finalCheck: {
      question: "A playground is shaped like a rectangle with side lengths 12 meters and 7 meters. What is the perimeter? Show how you know.",
      teacherNote: "Next Steps: Watch for students who know the formula but still miss a side when adding.",
    },
    boss: {
      title: "Challenge Zone: Shape Boss",
      subtitle: "Ready for a multi-step geometry mission?",
      scenario: "A garden is shaped like a rectangle that is 9 meters long and 4 meters wide. A fence will go all the way around it. How much fencing is needed? If each meter of fence costs $3, what is the total cost?",
      hints: [
        "Strategy: Find the perimeter first by adding all four sides.",
        "Hint 2: A rectangle has two long sides and two short sides.",
        "Hint 3: Multiply the perimeter by 3 to find the cost.",
      ],
      strategies: ["Sketch the shape", "Label all side lengths", "Check units at the end"],
    },
    independent: {
      levels: [
        {
          id: "easy",
          title: "Level 1: Warm-Up",
          difficulty: "Easy",
          accent: "green",
          note: "✔️ Label your units",
          problems: [
            { id: "i1", number: "1", prompt: "Perimeter of an equilateral triangle with side 5 cm = ?", answer: "15" },
            { id: "i2", number: "2", prompt: "How many sides does an octagon have?", answer: "8" },
          ],
        },
        {
          id: "medium",
          title: "Level 2: Challenge",
          difficulty: "Medium",
          accent: "gold",
          note: "✔️ Explain the attributes you used",
          problems: [
            { id: "i3", number: "3", prompt: "Rectangle 10 by 3. Perimeter = ?", answer: "26" },
            { id: "i4", number: "4", prompt: "How many vertices does a hexagon have?", answer: "6" },
          ],
        },
        {
          id: "hard",
          title: "Boss Battle",
          difficulty: "Hard",
          accent: "red",
          note: "✔️ Explain how you checked your answer",
          problems: [
            { id: "i5", number: "5", prompt: "A pentagon has five sides of 4 cm each. Perimeter = ?", answer: "20" },
          ],
        },
      ],
    },
  },
};